### ISSUE TITLE
Can't get macros to work

### ISSUE THREAD

**Issue by DanielApt** [pierreant-p/jinja-loader#1]
We're trying to use jinja-loader in combination with webpack. Sadly we're already failing with the most basic macro. 

Could you maybe share a working example with a macro?

Also, to help illustrate the issue we have two files:

``` jinja
{# template.jinja2 #}
{% from 'template-macro.jinja2' import template %}
{{template(name)}}
```

``` jinja
{# template-macro.jinja2 #}
<p>Hello {{name}}</p>
```

We then try to include `template.jinja2`:

``` js
require('./views/template.jinja2');

var Nunjucks = require('nunjucks');

var PrecompiledLoader = Nunjucks.Loader.extend( {

    getSource: function ( name ) {
        return {
            src: {
                type: 'code',
                obj: window.nunjucksPrecompiled[ name ]
            },
            path: name
        };
    }

} );

var environment = new Nunjucks.Environment('');

console.log(environment.render('template.jinja2'));
```

Firstly webpack attempts to find `template-macro.jinja2` in `/node-modules`. Even after correcting we're still seeing issues (in the browser):

```
Uncaught Template render error: (template.jinja2)
  TypeError: Cannot read property 'resolve' of undefined
```

Please let me know if you need any more info.

**Comment by pierreant-p** [comment]
Thx for the report. Can you specify:
- The basic layout (file/directory structure) of the project
- Your webpack config? (`webpack.config.js`) ?

**Comment by DanielApt** [comment]
Sure thing
**The file structure**

```
/node-modules
/views
--template.jinja2
--template-macro.jinja2
bundle.js
entry.js
index.html
webpack.config.js
```

**webpack.config.js**

``` js
module.exports = {
    entry: './entry',
    output: {
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.jinja2$/, loader: 'jinja-loader',
                query: {
                    root: __dirname + '/views/'
                }
            }
        ]
    }
};
```

**Comment by pierreant-p** [comment]
Does it work if you add you template path in the resolve option of the webpack confifg:

```
module.exports = {
   ...
resolve: {
        root: [
            path.join( __dirname, 'views/' )  // note: must be absolute
        ]
 }
   ...
};
```

**Comment by DanielApt** [comment]
That seems to have done the trick! Thank you.

**Comment by pierreant-p** [comment]
Nice. Let me know if you have other issues, or improvement ideas (there's a ton of room for improvement :) )
