### ISSUE TITLE
loaderUtils.parseQuery is deprecated

### ISSUE THREAD

**Issue by tiagojdf** [pierreant-p/jinja-loader#7]
When running a webpack build, webpack throws the following warning:
```
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
  at Object.parseQuery (/var/www/prod/node_modules/loader-utils/index.js:78:3)
``` 
As stated in the warning, you can get more info in the [loader-utils issue 56](https://github.com/webpack/loader-utils/issues/56), but the basic idea is that you should replace `loaderUtils.parseQuery` in [here](loader/blob/184f8ff82dd10f493be6687f1ffe5e8a2db328ec/index.js#L30) with:

 * getOptions - the only way to get the loader options. It will look like this:

**Comment by pierreant-p** [comment]
@Tiagojdferreira feel free to open a pull request !
